version: "3.8"
services:
  solana-rpc-1:
    image: solanalabs/solana:v1.17.18
    ports:
      - "8902:8899"  # Cambié el puerto externo a 8902
    restart: unless-stopped

  solana-rpc-2:
    image: solanalabs/solana:v1.17.18
    ports:
      - "8903:8899"  # Cambié el puerto externo a 8903
    restart: unless-stopped

  solana-rpc-3:
    image: solanalabs/solana:v1.17.18
    ports:
      - "8904:8899"  # Cambié el puerto externo a 8904
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-marisolvrs.fun.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - solana-rpc-1
      - solana-rpc-2
      - solana-rpc-3
    restart: unless-stopped

