apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-acme-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Si no tienes una StorageClass personalizada, puedes usar 'standard'
  hostPath:
    path: /mnt/data/traefik-acme  # El directorio en el nodo donde se guardarán los datos (puedes cambiarlo)
