ports:
  web:
    expose: 
      enabled: true  # Cambié a un objeto con la propiedad "enabled"
      entryPoint: web
  websecure:
    tls:
      enabled: true
    entryPoint: websecure

certificatesResolvers:
  letsencrypt:
    acme:
      email: marisolylucky@mail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=marisolylucky@mail.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

